### PR TITLE
Added google colab links

### PR DESCRIPTION
**Pull request by param087**

### CODE REVIEW

**Comment by rxwei** [comment]
This PR seems very huge and seems more than just adding Colab links. Perhaps it's an oversight?

**Comment by param087** [comment]
In this PR, 
1. I have removed local repo based swiftPM installation command(will add in README) and kept only git-based swiftPM installation to make common notebooks for both Colab and Github.
2. Added Colab link to notebooks.
3. Re-run the notebooks with git-based swiftPM installation, most of the changes are due to warnings and re-run.

**Review by dan-zheng — APPROVED** [review]

**Review by rxwei — APPROVED** [review]

**Comment by gsparsh220598** [comment]
Hey maintainers, I'm interested in contributing to this project. Could you please link me to the gitter channel where I can ask doubts.
@dan-zheng @rxwei @param087

**Comment by param087** [comment]
hey @gsparsh220598,
swiftML is a Google Summer of Code project of me and Victor. For time being we have not set up any Gitter or Slack channel. If you have any question you can ask me or Victor. 
Good PRs are always welcome.

**Comment by gsparsh220598** [comment]
Hey Param, Thanks for replying. Could you tell me how can I test the
libraries you have built so that I can understand the codebase?
I am looking forward to working with this library and potentially
contributing to it.
Thank You

**Comment by param087** [comment]
Is it possible to create an issue and continue this discussion over that.

**Comment by gsparsh220598** [comment]
Yes sure. No problem

**Pull request merged**
